# Generated by Django 3.0.6 on 2020-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200517_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
