# Generated by Django 2.2.16 on 2020-10-06 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
